In [1]:
import pandas as pd

In [2]:
quast_df = pd.read_csv('quast_mapping_file.tsv',sep="\t",index_col=0)
quast_df.head(1)

             # contigs  Total length  GC (%)    N50   N90      auN  L50  L90
key
LG284_bin.1        731       9179790   34.42  15231  5694  51058.8  130  530

In [3]:
checkm_df = pd.read_csv('checkm_mapping_file.tsv',sep="\t",index_col = 0)
checkm_df.head(1)

,Completeness,Contamination,Genome size,N50 (contigs),N50 (scaffolds)
key,,,,,
LG284_bin.1,64.88138,25.197699,9179790,15231,15231

In [4]:
df = checkm_df.join(quast_df)
df.head(1)

,Completeness,Contamination,Genome size,N50 (contigs),N50 (scaffolds),# contigs,Total length,GC (%),N50,N90,auN,L50,L90
key,,,,,,,,,,,,,
LG284_bin.1,64.88138,25.197699,9179790,15231,15231,731,9179790,34.42,15231,5694,51058.8,130,530

In [5]:
df.columns

Index(['Completeness', 'Contamination', 'Genome size', 'N50 (contigs)',
       'N50 (scaffolds)', '# contigs', 'Total length', 'GC (%)', 'N50', 'N90',
       'auN', 'L50', 'L90'],
      dtype='object')

In [6]:
df.drop(columns=['N50 (contigs)','N50 (scaffolds)','Total length'],inplace=True)
df.head(1)

,Completeness,Contamination,Genome size,# contigs,GC (%),N50,N90,auN,L50,L90
key,,,,,,,,,,
LG284_bin.1,64.88138,25.197699,9179790,731,34.42,15231,5694,51058.8,130,530

In [7]:
kaiju = pd.read_csv('kaiju_mapping_file.tsv',sep="\t",index_col=0)
kaiju.head(1)

,top_taxon,percent,reads,remaining
key,,,,
LG275_bin.1,cannot be assigned to a (non-viral) species,43.75,35,"['Priestia megaterium, 35.0, 28.0', 'Priestia ..."

In [8]:
df = df.join(kaiju)
df.head(1)

,Completeness,Contamination,Genome size,# contigs,GC (%),N50,N90,auN,L50,L90,top_taxon,percent,reads,remaining
key,,,,,,,,,,,,,,
LG284_bin.1,64.88138,25.197699,9179790,731,34.42,15231,5694,51058.8,130,530,Candida albicans,72.22982,528,"['Candida africana, 17.099863, 125.0', 'cannot..."

In [9]:
df.columns

Index(['Completeness', 'Contamination', 'Genome size', '# contigs', 'GC (%)',
       'N50', 'N90', 'auN', 'L50', 'L90', 'top_taxon', 'percent', 'reads',
       'remaining'],
      dtype='object')

In [10]:
new_order = ['top_taxon', 'percent', 'reads', 'Completeness', 'Contamination', 
             'Genome size', '# contigs', 'GC (%)', 'N50', 'N90', 'auN', 'L50', 'L90', 'remaining']

In [11]:
df = df[new_order]
df.head(1)

,top_taxon,percent,reads,Completeness,Contamination,Genome size,# contigs,GC (%),N50,N90,auN,L50,L90,remaining
key,,,,,,,,,,,,,,
LG284_bin.1,Candida albicans,72.22982,528,64.88138,25.197699,9179790,731,34.42,15231,5694,51058.8,130,530,"['Candida africana, 17.099863, 125.0', 'cannot..."

In [12]:
df.rename(columns={'percent': 'kaiju percent', 'reads': 'kaiju reads'}, inplace=True)
df.head(1)

,top_taxon,kaiju percent,kaiju reads,Completeness,Contamination,Genome size,# contigs,GC (%),N50,N90,auN,L50,L90,remaining
key,,,,,,,,,,,,,,
LG284_bin.1,Candida albicans,72.22982,528,64.88138,25.197699,9179790,731,34.42,15231,5694,51058.8,130,530,"['Candida africana, 17.099863, 125.0', 'cannot..."

In [13]:
#df.to_csv('metagenome_assembly_and_classification.tsv',sep="\t")